### ISSUE TITLE
Download necessary chianti files directly remove to remove dependancy on local ssw install.

### ISSUE THREAD

**Issue by samaloney** [sunpy/sunxspex#22]
Now that SSW updates have to be over http the entire SSW tree is web accessible so we can just download the chianti files from [here](https://hesperia.gsfc.nasa.gov/ssw/packages/xray/dbase/chianti). If we wanted to get fancy we could check for a local ssw versions first.

**Comment by samaloney** [comment]
Use `sunpy.data.manager` to manage  this.

**Comment by Cadair** [comment]
https://docs.sunpy.org/en/latest/dev_guide/remote_data.html :smile:
