### ISSUE TITLE
Local file paths currently hardcoded

### ISSUE THREAD

**Issue by DanRyanIrish** [sunpy/sunxspex#8]
The path to the ```chianti_lines_1_10_v71.sav``` file is currently hardcoded as the location on my machine.  This needs to be treated more intelligently.  Perhaps it should live in a data directory or be downloaded and stored via sunpy's database.

**Comment by samaloney** [comment]
Could probably pull these from [here](http://darts.jaxa.jp/pub/solar/ssw/packages/xray/dbase/chianti/) and store in sunpy dir as a temporary measure to make it just work out of the box. Also if the plan is to only support python 3.6 or 3.5 plus can use pathlib to clean up all path related code.
